/**
 * Denial-code reference data for /edi/835/denial-codes. One entry per code
 * drives one statically-generated page (see
 * app/edi/[code]/denial-codes/[carc]/page.tsx), because denial analysts search
 * individual codes — "CO-45", "PR-1", "N130" — one at a time.
 *
 * Two code systems appear on an 835 remittance:
 *   - CARC (Claim Adjustment Reason Codes): why an amount wasn't paid. Numeric,
 *     always paired with a group code (CO / PR / OA / PI / CR) in the CAS segment.
 *   - RARC (Remittance Advice Remark Codes): extra context. Start with M, N, or MA.
 *
 * All prose here is our own plain-English wording — nothing is copied from the
 * official X12/WPC code lists. The `short` field paraphrases the standard
 * description; `plain`, `why`, and `fix` are explanatory. This is a curated set
 * of the codes analysts hit most; the official lists are maintained by X12 and
 * new entries can be appended here as they're needed.
 */
export type CodeSystem = "CARC" | "RARC";

/** X12 claim adjustment group codes — who the adjustment belongs to. */
export type GroupCode = "CO" | "PR" | "OA" | "PI" | "CR";

export interface DenialCode {
  code: string; // "45", "97", "N130"
  system: CodeSystem;
  /** Typical group code for a CARC (the prefix in "CO-45"). RARCs have none. */
  group?: GroupCode;
  /** Other group codes this CARC commonly appears under. */
  alsoGroups?: GroupCode[];
  /** One-line paraphrase of the standard description. */
  short: string;
  /** What it actually means, in plain English. */
  plain: string;
  /** Why a payer sends it. */
  why: string;
  /** What a billing team typically does about it. */
  fix: string;
  category: CategoryKey;
}

export type CategoryKey =
  | "patient"
  | "contractual"
  | "coverage"
  | "auth"
  | "coding"
  | "duplicate"
  | "timely"
  | "cob"
  | "info";

export const CATEGORIES: Record<CategoryKey, { label: string; blurb: string }> = {
  patient: { label: "Patient responsibility", blurb: "Amounts the patient owes — deductible, coinsurance, copay." },
  contractual: { label: "Contractual", blurb: "Write-offs the provider absorbs under the payer contract." },
  coverage: { label: "Coverage / benefits", blurb: "The service isn't covered under the plan or benefit period." },
  auth: { label: "Authorization", blurb: "Prior authorization, referral, or precertification problems." },
  coding: { label: "Coding / billing", blurb: "Code, modifier, diagnosis, or claim-data errors." },
  duplicate: { label: "Duplicate", blurb: "The claim or service has already been processed." },
  timely: { label: "Timely filing", blurb: "The claim was submitted outside the filing window." },
  cob: { label: "Coordination of benefits", blurb: "Another payer is primary or has already adjudicated." },
  info: { label: "Missing information", blurb: "Required data or documentation is missing or invalid." },
};

export const GROUP_CODES: Record<GroupCode, { label: string; blurb: string }> = {
  CO: {
    label: "Contractual Obligation",
    blurb:
      "The provider eats this amount under the payer contract. It can't be billed to the patient — it's a write-off.",
  },
  PR: {
    label: "Patient Responsibility",
    blurb: "The patient owes this amount — a deductible, coinsurance, or copay. You can bill them for it.",
  },
  OA: {
    label: "Other Adjustment",
    blurb: "Used when neither contractual nor patient responsibility fits — often coordination of benefits.",
  },
  PI: {
    label: "Payer Initiated Reduction",
    blurb: "The payer is taking the adjustment on its own initiative, not because of the contract or the patient.",
  },
  CR: {
    label: "Correction and Reversal",
    blurb: "Reverses or corrects a previously adjudicated claim. Usually paired with a replacement entry.",
  },
};

export const DENIAL_CODES: DenialCode[] = [
  // ---- Patient responsibility ----
  {
    code: "1",
    system: "CARC",
    group: "PR",
    short: "Deductible amount.",
    plain: "This amount was applied to the patient's deductible.",
    why: "The patient hadn't met their plan deductible yet, so the payer pushes this dollar amount to the patient instead of paying it.",
    fix: "Bill the patient for the deductible amount. Nothing to appeal — this is normal patient responsibility.",
    category: "patient",
  },
  {
    code: "2",
    system: "CARC",
    group: "PR",
    short: "Coinsurance amount.",
    plain: "This is the patient's coinsurance share of the allowed amount.",
    why: "After the deductible, most plans split the allowed amount — e.g. 80/20. The 20% the patient owes shows up here.",
    fix: "Bill the patient for the coinsurance. Verify the percentage against the patient's plan if it looks off.",
    category: "patient",
  },
  {
    code: "3",
    system: "CARC",
    group: "PR",
    short: "Co-payment amount.",
    plain: "This is the patient's fixed copay for the visit or service.",
    why: "The plan charges a flat copay (e.g. $30 for an office visit), collected from the patient regardless of the allowed amount.",
    fix: "Collect the copay from the patient. It's often collected at the front desk, so reconcile against what was already taken.",
    category: "patient",
  },
  // ---- Coding / billing ----
  {
    code: "4",
    system: "CARC",
    group: "CO",
    short: "Procedure code inconsistent with the modifier, or a required modifier is missing.",
    plain: "The procedure code and its modifier don't agree, or a modifier the code requires wasn't billed.",
    why: "Many CPT/HCPCS codes need a specific modifier (laterality, professional/technical component, etc.). A missing or contradictory modifier triggers this.",
    fix: "Check the code's modifier rules, add or correct the modifier, and resubmit a corrected claim.",
    category: "coding",
  },
  {
    code: "5",
    system: "CARC",
    group: "CO",
    short: "Procedure code or bill type is inconsistent with the place of service.",
    plain: "The service was billed with a place of service that doesn't match the procedure or bill type.",
    why: "Some procedures are only payable in certain settings (office, inpatient, ASC). A mismatch — e.g. an inpatient-only procedure billed as office — denies.",
    fix: "Confirm where the service was actually rendered, correct the place-of-service code, and resubmit.",
    category: "coding",
  },
  {
    code: "6",
    system: "CARC",
    group: "CO",
    short: "Procedure or revenue code is inconsistent with the patient's age.",
    plain: "The code billed doesn't fit the patient's age.",
    why: "Some procedures are age-restricted (pediatric vs. adult, screening age windows). The payer's edit caught an age mismatch.",
    fix: "Verify the patient's date of birth and the code's age range. Correct the DOB or code as appropriate and resubmit.",
    category: "coding",
  },
  {
    code: "8",
    system: "CARC",
    group: "CO",
    short: "Procedure code is inconsistent with the provider type or specialty.",
    plain: "This type of provider isn't expected to bill this procedure.",
    why: "The payer maps procedures to provider specialties. A code outside the rendering provider's specialty taxonomy can deny.",
    fix: "Confirm the rendering provider's taxonomy/specialty on file with the payer and that the code is appropriate; correct enrollment or the claim as needed.",
    category: "coding",
  },
  {
    code: "9",
    system: "CARC",
    group: "CO",
    short: "Diagnosis is inconsistent with the patient's age.",
    plain: "The diagnosis doesn't fit the patient's age.",
    why: "Some ICD-10 diagnoses are age-specific (e.g. newborn or geriatric conditions). An age mismatch fails the edit.",
    fix: "Check the DOB and the diagnosis. Correct whichever is wrong and resubmit a corrected claim.",
    category: "coding",
  },
  {
    code: "11",
    system: "CARC",
    group: "CO",
    short: "The diagnosis is inconsistent with the procedure.",
    plain: "The diagnosis on the claim doesn't support the procedure that was billed.",
    why: "Payers run medical-necessity edits (LCD/NCD) linking procedures to acceptable diagnoses. A procedure with an unsupported diagnosis denies.",
    fix: "Review documentation for a supporting diagnosis, correct the diagnosis pointer or add the right ICD-10 code, and resubmit.",
    category: "coding",
  },
  {
    code: "16",
    system: "CARC",
    group: "CO",
    alsoGroups: ["PI"],
    short: "The claim or service lacks information or has a submission/billing error.",
    plain: "Something required is missing or wrong — the accompanying RARC tells you exactly what.",
    why: "This is a catch-all. It's almost always paired with a RARC (an M/N code) that names the specific missing or invalid field.",
    fix: "Read the RARC remark sent alongside it — that's the actionable part. Fix the named field and resubmit.",
    category: "info",
  },
  {
    code: "18",
    system: "CARC",
    group: "OA",
    alsoGroups: ["CO"],
    short: "Exact duplicate claim or service.",
    plain: "This claim or line is a duplicate of one already received.",
    why: "The same claim was submitted more than once, or a line repeats a service already adjudicated on another claim.",
    fix: "Don't resubmit. Check the original claim's status; if it's still unpaid, follow up on the original rather than rebilling.",
    category: "duplicate",
  },
  {
    code: "19",
    system: "CARC",
    group: "OA",
    short: "This is a work-related injury — liability of the Workers' Compensation carrier.",
    plain: "The payer believes this should be billed to Workers' Comp, not the health plan.",
    why: "The injury was flagged as work-related, making the WC carrier responsible.",
    fix: "Bill the Workers' Compensation carrier. If it isn't work-related, supply documentation and appeal.",
    category: "cob",
  },
  {
    code: "22",
    system: "CARC",
    group: "OA",
    short: "This care may be covered by another payer per coordination of benefits.",
    plain: "Another insurer may be primary; this payer is coordinating benefits.",
    why: "The payer's records show other coverage that should be billed first.",
    fix: "Identify the primary payer, bill them first, then submit to this payer as secondary with the primary EOB.",
    category: "cob",
  },
  {
    code: "23",
    system: "CARC",
    group: "OA",
    short: "Impact of prior payer(s) adjudication, including payments and/or adjustments.",
    plain: "This adjustment reflects what the primary payer already did.",
    why: "On a secondary claim, the payer accounts for the primary's payment and adjustments before calculating its own.",
    fix: "Usually informational on a secondary remit. Confirm the primary's payment was reported correctly; no action if balances reconcile.",
    category: "cob",
  },
  {
    code: "24",
    system: "CARC",
    group: "CO",
    short: "Charges are covered under a capitation agreement or managed care plan.",
    plain: "This service is paid through capitation, not fee-for-service.",
    why: "The provider has a capitated contract for this member, so the payer doesn't pay per claim.",
    fix: "No fee-for-service payment is due. Confirm the member's capitation arrangement; don't bill the patient.",
    category: "contractual",
  },
  {
    code: "26",
    system: "CARC",
    group: "PR",
    short: "Expenses incurred prior to coverage.",
    plain: "The service happened before the patient's coverage started.",
    why: "The date of service is earlier than the member's effective date.",
    fix: "Verify the coverage effective date. If the date of service is correct and uncovered, bill the patient or the correct prior payer.",
    category: "coverage",
  },
  {
    code: "27",
    system: "CARC",
    group: "CO",
    alsoGroups: ["PR"],
    short: "Expenses incurred after coverage terminated.",
    plain: "The service happened after the patient's coverage ended.",
    why: "The date of service falls after the member's termination date.",
    fix: "Confirm the termination date with eligibility. If coverage truly ended, bill the patient or the active payer for that date.",
    category: "coverage",
  },
  {
    code: "29",
    system: "CARC",
    group: "CO",
    short: "The time limit for filing has expired.",
    plain: "The claim was submitted after the payer's timely-filing deadline.",
    why: "Each payer has a filing window (often 90–365 days from the date of service). This claim arrived too late.",
    fix: "If you have proof of timely submission (clearinghouse reports, prior denials), appeal with it. Otherwise the amount is usually a write-off.",
    category: "timely",
  },
  {
    code: "31",
    system: "CARC",
    group: "PR",
    alsoGroups: ["CO"],
    short: "Patient cannot be identified as our insured.",
    plain: "The payer can't match the patient to an active member.",
    why: "The member ID, name, or date of birth on the claim doesn't match the payer's eligibility file.",
    fix: "Re-verify the patient's ID card and eligibility, correct the demographics or member ID, and resubmit.",
    category: "info",
  },
  {
    code: "39",
    system: "CARC",
    group: "CO",
    short: "Services denied at the time authorization or precertification was requested.",
    plain: "The payer already declined to authorize this service.",
    why: "An auth request for this service was denied before the claim was ever submitted.",
    fix: "Review the original authorization denial. Appeal with clinical documentation if the service was warranted.",
    category: "auth",
  },
  {
    code: "40",
    system: "CARC",
    group: "CO",
    short: "Charges do not meet qualifications for emergent/urgent care.",
    plain: "The payer didn't consider this an emergency, so emergency benefits don't apply.",
    why: "The diagnosis or documentation didn't support the emergent/urgent level billed.",
    fix: "Submit records supporting the urgency of the visit and appeal, or rebill under the correct level of care.",
    category: "coverage",
  },
  {
    code: "45",
    system: "CARC",
    group: "CO",
    short: "Charge exceeds the fee schedule, maximum allowable, or contracted amount.",
    plain: "You billed more than the contracted/allowed amount; the difference is a write-off.",
    why: "This is the single most common adjustment on an 835. The payer pays its allowed amount and writes off the rest under the contract — it isn't a denial of payment.",
    fix: "Usually no action: it's an expected contractual write-off, not billable to the patient. If the allowed amount looks wrong, verify your contracted fee schedule with the payer.",
    category: "contractual",
  },
  {
    code: "49",
    system: "CARC",
    group: "PR",
    alsoGroups: ["CO"],
    short: "Routine/preventive exam or screening procedure not covered.",
    plain: "This is a routine or preventive service the plan doesn't cover.",
    why: "The plan excludes the routine exam or screening as billed, or it was performed outside the covered frequency.",
    fix: "Check the plan's preventive benefits and frequency limits. If non-covered, bill the patient (an ABN/notice may apply).",
    category: "coverage",
  },
  {
    code: "50",
    system: "CARC",
    group: "CO",
    alsoGroups: ["PR"],
    short: "Non-covered service — not deemed a medical necessity by the payer.",
    plain: "The payer decided the service wasn't medically necessary.",
    why: "The diagnosis and documentation didn't meet the payer's medical-necessity criteria (LCD/NCD or plan policy).",
    fix: "Review the coverage policy, gather supporting clinical documentation, and appeal — or bill the patient if a valid ABN was obtained.",
    category: "coverage",
  },
  {
    code: "54",
    system: "CARC",
    group: "CO",
    short: "Multiple physicians/assistants are not covered in this case.",
    plain: "The plan won't pay for more than one provider on this service.",
    why: "An assistant surgeon or additional physician was billed where the payer's policy doesn't allow it.",
    fix: "Verify assistant-surgeon eligibility for the procedure; appeal with documentation if the second provider was required.",
    category: "coverage",
  },
  {
    code: "55",
    system: "CARC",
    group: "CO",
    short: "Procedure/treatment is deemed experimental or investigational.",
    plain: "The payer considers this treatment experimental and won't cover it.",
    why: "The service isn't recognized as established/effective under the payer's policy.",
    fix: "Appeal with peer-reviewed evidence and medical records if the treatment is supported, or bill the patient with a proper notice.",
    category: "coverage",
  },
  {
    code: "58",
    system: "CARC",
    group: "CO",
    short: "Treatment was rendered in an inappropriate or invalid place of service.",
    plain: "The payer says this service shouldn't have been done in this setting.",
    why: "The site of care doesn't match where the payer expects the service to be performed.",
    fix: "Confirm the correct place of service; correct and resubmit, or appeal with documentation of medical necessity for the setting.",
    category: "coding",
  },
  {
    code: "59",
    system: "CARC",
    group: "CO",
    short: "Charges adjusted based on multiple or concurrent procedure rules.",
    plain: "Payment was reduced because multiple procedures were performed together.",
    why: "Under multiple-procedure rules, secondary procedures in the same session are paid at a reduced rate.",
    fix: "Usually expected. Confirm the reduction matches the payer's multiple-procedure policy; no action if correct.",
    category: "contractual",
  },
  {
    code: "96",
    system: "CARC",
    group: "CO",
    alsoGroups: ["PR"],
    short: "Non-covered charge(s).",
    plain: "The service isn't covered — the accompanying remark says why.",
    why: "A broad non-coverage code, almost always paired with a RARC that gives the specific reason (benefit exclusion, statutory non-coverage, etc.).",
    fix: "Read the paired RARC. If CO, it's a write-off; if PR, it's billable to the patient. Appeal if coverage was expected.",
    category: "coverage",
  },
  {
    code: "97",
    system: "CARC",
    group: "CO",
    short: "Payment is included in the allowance for another service already adjudicated (bundling).",
    plain: "This service is bundled into another one that was already paid, so it isn't paid separately.",
    why: "Under bundling/NCCI rules, the payment for this line is considered part of a primary service's allowance.",
    fix: "Check whether a modifier (e.g. 25 or 59) was appropriate to unbundle. If so, correct and resubmit; otherwise it's a write-off.",
    category: "contractual",
  },
  {
    code: "100",
    system: "CARC",
    group: "OA",
    short: "Payment made to the patient, insured, or responsible party.",
    plain: "The payer paid the patient directly instead of the provider.",
    why: "The plan or assignment situation directed payment to the member.",
    fix: "Collect from the patient, who has received the payment. Review assignment-of-benefits setup to prevent recurrence.",
    category: "patient",
  },
  {
    code: "107",
    system: "CARC",
    group: "CO",
    short: "The related or qualifying claim/service was not identified on this claim.",
    plain: "This service depends on another one that wasn't linked on the claim.",
    why: "Some procedures are only payable alongside a qualifying service that must be referenced; it was missing.",
    fix: "Add the required reference to the qualifying claim/service and resubmit a corrected claim.",
    category: "coding",
  },
  {
    code: "109",
    system: "CARC",
    group: "CO",
    alsoGroups: ["OA"],
    short: "Claim/service not covered by this payer/contractor — send to the correct payer.",
    plain: "You billed the wrong payer for this service.",
    why: "The service or member belongs to a different payer, plan, or contractor (common with Medicare Advantage vs. traditional Medicare).",
    fix: "Identify the correct payer and rebill them. Verify the member's active plan in eligibility.",
    category: "cob",
  },
  {
    code: "110",
    system: "CARC",
    group: "CO",
    short: "Billing date predates the service date.",
    plain: "The claim's billing date is earlier than the date of service.",
    why: "A data-entry or system error put a billing/submission date before the service actually occurred.",
    fix: "Correct the dates on the claim and resubmit.",
    category: "coding",
  },
  {
    code: "119",
    system: "CARC",
    group: "CO",
    alsoGroups: ["PR"],
    short: "Benefit maximum for this time period or occurrence has been reached.",
    plain: "The patient has used up this benefit's limit.",
    why: "The plan caps visits, dollars, or units for this benefit, and the patient hit the cap.",
    fix: "Verify the benefit limit. Remaining charges are typically patient responsibility; bill the patient or appeal if the cap was applied in error.",
    category: "coverage",
  },
  {
    code: "125",
    system: "CARC",
    group: "CO",
    short: "Submission/billing error(s).",
    plain: "There's an error in how the claim was submitted — the remark gives specifics.",
    why: "A formatting or data error prevented normal adjudication; a paired RARC names it.",
    fix: "Read the RARC, correct the identified error, and resubmit.",
    category: "info",
  },
  {
    code: "129",
    system: "CARC",
    group: "CO",
    short: "Prior processing information appears incorrect.",
    plain: "Information about an earlier payer's processing looks wrong.",
    why: "On a secondary/tertiary claim, the reported prior-payer payment or adjustment doesn't add up.",
    fix: "Re-check the primary EOB amounts you entered, correct them, and resubmit the secondary claim.",
    category: "cob",
  },
  {
    code: "133",
    system: "CARC",
    group: "OA",
    short: "The disposition of the claim/service is pending further review.",
    plain: "The payer hasn't finished adjudicating — it's still under review.",
    why: "The claim needs additional review before a final decision.",
    fix: "No resubmission. Wait for the follow-up remit; supply any requested documentation promptly.",
    category: "info",
  },
  {
    code: "140",
    system: "CARC",
    group: "PR",
    short: "Patient/insured health identification number and name do not match.",
    plain: "The member ID and name on the claim don't match the payer's records.",
    why: "A typo or mismatched ID/name combination failed the eligibility match.",
    fix: "Confirm the ID and spelling against the patient's card, correct the claim, and resubmit.",
    category: "info",
  },
  {
    code: "146",
    system: "CARC",
    group: "CO",
    short: "Diagnosis was invalid for the date(s) of service reported.",
    plain: "The diagnosis code wasn't valid on the date the service was performed.",
    why: "ICD-10 codes are added and retired over time; the code wasn't active for that date of service.",
    fix: "Use the diagnosis code valid for that date of service and resubmit a corrected claim.",
    category: "coding",
  },
  {
    code: "147",
    system: "CARC",
    group: "CO",
    short: "Provider contracted/negotiated rate has expired or is not on file.",
    plain: "The payer has no current contracted rate for this provider.",
    why: "The provider's contract lapsed or wasn't loaded, so the payer can't price the claim.",
    fix: "Confirm the contract/credentialing status with the payer's provider relations; resubmit once the rate is loaded.",
    category: "contractual",
  },
  {
    code: "151",
    system: "CARC",
    group: "CO",
    short: "Payer deems the information submitted does not support this many services.",
    plain: "You billed more units/frequency than the documentation supports.",
    why: "The number of services exceeds what the payer's policy or your records justify.",
    fix: "Verify the units billed against documentation; correct the count or appeal with records supporting the frequency.",
    category: "coverage",
  },
  {
    code: "167",
    system: "CARC",
    group: "CO",
    short: "This diagnosis is not covered.",
    plain: "The plan excludes the diagnosis billed.",
    why: "The diagnosis falls under a plan exclusion or non-covered condition.",
    fix: "Confirm the correct diagnosis. If it's truly excluded, the charge may be patient responsibility; appeal if coded in error.",
    category: "coverage",
  },
  {
    code: "170",
    system: "CARC",
    group: "CO",
    short: "Payment denied when performed/billed by this type of provider.",
    plain: "This provider type isn't allowed to bill this service.",
    why: "The payer restricts the service to certain provider types, and the billing provider isn't one.",
    fix: "Confirm the correct billing/rendering provider and their eligibility for the service; rebill correctly if appropriate.",
    category: "coverage",
  },
  {
    code: "181",
    system: "CARC",
    group: "CO",
    short: "Procedure code was invalid on the date of service.",
    plain: "The CPT/HCPCS code wasn't valid for that date of service.",
    why: "The procedure code was added or deleted such that it wasn't active on the service date.",
    fix: "Use the procedure code valid for that date of service and resubmit.",
    category: "coding",
  },
  {
    code: "182",
    system: "CARC",
    group: "CO",
    short: "Procedure modifier was invalid on the date of service.",
    plain: "The modifier wasn't valid for that date of service.",
    why: "The modifier was retired or not yet active on the service date, or it's not allowed with the code.",
    fix: "Correct the modifier to one valid for that date and code, then resubmit.",
    category: "coding",
  },
  {
    code: "185",
    system: "CARC",
    group: "CO",
    short: "The rendering provider is not eligible to perform the service billed.",
    plain: "The rendering provider isn't eligible to perform this service.",
    why: "The provider's credentials, enrollment, or scope don't cover the billed service.",
    fix: "Confirm the rendering provider's enrollment and eligibility for the service; correct the provider or credentialing and resubmit.",
    category: "coverage",
  },
  {
    code: "197",
    system: "CARC",
    group: "CO",
    short: "Precertification/authorization/notification/pre-treatment absent.",
    plain: "Required prior authorization wasn't obtained.",
    why: "The service needed precert/authorization and none was on file when the claim adjudicated.",
    fix: "Request a retro-authorization if the payer allows it, or appeal with documentation. Tighten front-end auth checks to prevent repeats.",
    category: "auth",
  },
  {
    code: "198",
    system: "CARC",
    group: "CO",
    short: "Precertification/authorization exceeded.",
    plain: "You billed beyond what the authorization approved.",
    why: "The units, visits, or dollar amount exceeded the approved authorization.",
    fix: "Bill within the authorized amount, or request an extended/additional authorization and appeal the excess.",
    category: "auth",
  },
  {
    code: "199",
    system: "CARC",
    group: "CO",
    short: "Revenue code and procedure code do not match.",
    plain: "On an institutional claim, the revenue code and procedure code conflict.",
    why: "The NUBC revenue code billed doesn't correspond to the HCPCS/CPT procedure on the line.",
    fix: "Correct the revenue-code/procedure pairing per the payer's billing guide and resubmit.",
    category: "coding",
  },
  {
    code: "204",
    system: "CARC",
    group: "PR",
    alsoGroups: ["CO"],
    short: "This service/equipment/drug is not covered under the patient's current benefit plan.",
    plain: "The patient's plan simply doesn't cover this item or service.",
    why: "It's a benefit exclusion for this member's plan — not a coding problem.",
    fix: "If PR, bill the patient (a notice/ABN may be required). Verify the plan's benefits; appeal only if it should be covered.",
    category: "coverage",
  },
  {
    code: "222",
    system: "CARC",
    group: "CO",
    short: "Exceeds the contracted maximum number of hours/days/units.",
    plain: "You billed more units than the contract allows for this period.",
    why: "The contract caps the number of hours, days, or units; the claim went over.",
    fix: "Confirm the contracted maximum; the excess is typically a write-off unless you can document medical necessity and appeal.",
    category: "contractual",
  },
  {
    code: "226",
    system: "CARC",
    group: "CO",
    short: "Information requested from the billing/rendering provider was not provided or was insufficient.",
    plain: "The payer asked you for information and didn't get enough of it.",
    why: "A records or information request went unanswered or came back incomplete.",
    fix: "Send the complete requested documentation and resubmit or appeal within the payer's window.",
    category: "info",
  },
  {
    code: "227",
    system: "CARC",
    group: "CO",
    short: "Information requested from the patient was not provided or was insufficient.",
    plain: "The payer needs information from the patient that it didn't receive.",
    why: "The payer requested data from the member (e.g. an accident or COB questionnaire) and got no adequate response.",
    fix: "Ask the patient to complete the payer's request (often a COB or accident form), then have the payer reprocess.",
    category: "info",
  },
  {
    code: "234",
    system: "CARC",
    group: "CO",
    short: "This procedure is not paid separately.",
    plain: "This procedure isn't reimbursed on its own.",
    why: "The service is considered part of another payment and has no separate allowance.",
    fix: "Confirm whether a modifier permits separate payment; otherwise it's a write-off.",
    category: "contractual",
  },
  {
    code: "236",
    system: "CARC",
    group: "CO",
    short: "Procedure/modifier combination is not compatible with another procedure (NCCI).",
    plain: "Two codes billed together violate an NCCI edit.",
    why: "National Correct Coding Initiative edits flag code pairs that shouldn't be billed together as submitted.",
    fix: "Review the NCCI edit; add an appropriate modifier if the services were distinct, or remove the conflicting line and resubmit.",
    category: "coding",
  },
  {
    code: "252",
    system: "CARC",
    group: "CO",
    short: "An attachment or other documentation is required to adjudicate.",
    plain: "The payer needs supporting documentation before it can pay.",
    why: "The claim type or service requires an attachment (records, invoice, report) that wasn't received.",
    fix: "Submit the required attachment per the paired RARC and the payer's process, then resubmit.",
    category: "info",
  },
  {
    code: "B7",
    system: "CARC",
    group: "CO",
    short: "Provider was not certified/eligible to be paid for this procedure on this date of service.",
    plain: "The provider wasn't eligible to be paid for this service on that date.",
    why: "An enrollment, certification, or effective-date gap meant the provider wasn't active for that service/date.",
    fix: "Verify the provider's enrollment effective dates with the payer; correct credentialing and resubmit once active.",
    category: "coverage",
  },
  {
    code: "B9",
    system: "CARC",
    group: "CO",
    short: "Patient is enrolled in a Hospice.",
    plain: "The patient is in hospice, so this service is handled under the hospice benefit.",
    why: "Services related to a hospice patient's terminal condition are paid through the hospice, not separately.",
    fix: "Bill the hospice provider, or append the appropriate modifier if the service is unrelated to the terminal diagnosis and appeal.",
    category: "coverage",
  },
  {
    code: "B15",
    system: "CARC",
    group: "CO",
    short: "This service requires a qualifying service/procedure to have been received and covered.",
    plain: "This service is only payable when a required companion service was also covered.",
    why: "The payer requires a qualifying procedure to be present/covered, and it wasn't.",
    fix: "Bill the qualifying service (or reference it if already paid) and resubmit.",
    category: "coding",
  },

  // ---- RARC (remark codes) ----
  {
    code: "M15",
    system: "RARC",
    short: "Separately billed services/tests have been bundled — they are not separately payable.",
    plain: "The services you billed separately are considered one bundled service.",
    why: "Accompanies a bundling adjustment (often CARC 97): the line is part of another service's payment.",
    fix: "Check for an unbundling modifier if the services were truly distinct; otherwise accept the bundle.",
    category: "contractual",
  },
  {
    code: "M16",
    system: "RARC",
    short: "Alert: please see the related bulletin, letter, or policy.",
    plain: "The payer is pointing you to a separate notice for details.",
    why: "Informational alert directing you to a policy bulletin or letter that explains the decision.",
    fix: "Locate the referenced bulletin/letter for the specifics; act on what it says.",
    category: "info",
  },
  {
    code: "M51",
    system: "RARC",
    short: "Missing/incomplete/invalid procedure code.",
    plain: "The procedure code is missing, incomplete, or invalid.",
    why: "The CPT/HCPCS on the line couldn't be read or isn't valid as submitted.",
    fix: "Supply a valid procedure code and resubmit a corrected claim.",
    category: "coding",
  },
  {
    code: "M76",
    system: "RARC",
    short: "Missing/incomplete/invalid diagnosis or condition.",
    plain: "The diagnosis code is missing, incomplete, or invalid.",
    why: "The ICD-10 diagnosis is absent or not valid as billed.",
    fix: "Add a valid, complete diagnosis code and resubmit.",
    category: "coding",
  },
  {
    code: "M77",
    system: "RARC",
    short: "Missing/incomplete/invalid place of service.",
    plain: "The place-of-service code is missing, incomplete, or invalid.",
    why: "The POS code on the claim couldn't be validated.",
    fix: "Enter the correct place-of-service code and resubmit.",
    category: "coding",
  },
  {
    code: "M80",
    system: "RARC",
    short: "Not covered when performed during the same session/date as a previously processed service.",
    plain: "This service isn't covered on the same day as another already-processed service.",
    why: "A same-session/same-day edit prevents paying this alongside the related service.",
    fix: "Verify the dates and whether a modifier applies; correct and resubmit or accept the denial.",
    category: "coding",
  },
  {
    code: "M81",
    system: "RARC",
    short: "You are required to code to the highest level of specificity.",
    plain: "The diagnosis must be coded to its most specific form.",
    why: "A truncated or unspecified ICD-10 code was used where a more specific one exists.",
    fix: "Recode the diagnosis to the highest level of specificity and resubmit.",
    category: "coding",
  },
  {
    code: "M119",
    system: "RARC",
    short: "Missing/incomplete/invalid National Drug Code (NDC).",
    plain: "The NDC for a drug is missing, incomplete, or invalid.",
    why: "Drug claims require a valid 11-digit NDC, which wasn't supplied correctly.",
    fix: "Add the correct NDC (and units/qualifier) and resubmit.",
    category: "coding",
  },
  {
    code: "MA01",
    system: "RARC",
    short: "Alert: if you disagree with the approved amount, you may appeal within the stated time limit.",
    plain: "This is your appeal-rights notice for the decision.",
    why: "Informational alert that accompanies a determination, telling you how and by when to appeal.",
    fix: "If you disagree, file an appeal within the stated deadline with supporting documentation.",
    category: "info",
  },
  {
    code: "MA04",
    system: "RARC",
    short: "Secondary payment cannot be considered without the primary payer's identity and payment information.",
    plain: "The payer can't process this as secondary without the primary's payment details.",
    why: "A secondary claim arrived without valid primary-payer adjudication information.",
    fix: "Attach the primary payer's EOB/ERA details (payment and adjustments) and resubmit the secondary claim.",
    category: "cob",
  },
  {
    code: "MA27",
    system: "RARC",
    short: "Missing/incomplete/invalid entitlement number or name shown on the claim.",
    plain: "The member's ID number or name is missing, incomplete, or invalid.",
    why: "The subscriber/patient identifier or name didn't match or wasn't readable.",
    fix: "Correct the member ID and name to match the ID card and resubmit.",
    category: "info",
  },
  {
    code: "MA40",
    system: "RARC",
    short: "Missing/incomplete/invalid admission date.",
    plain: "The admission date is missing, incomplete, or invalid.",
    why: "An institutional claim is missing a valid admission date.",
    fix: "Supply the correct admission date and resubmit.",
    category: "info",
  },
  {
    code: "MA61",
    system: "RARC",
    short: "Missing/incomplete/invalid Social Security or identity number.",
    plain: "The SSN or member identity number is missing, incomplete, or invalid.",
    why: "The identifier the payer matches on couldn't be validated.",
    fix: "Verify and correct the member's identity number and resubmit.",
    category: "info",
  },
  {
    code: "MA66",
    system: "RARC",
    short: "Missing/incomplete/invalid principal procedure code.",
    plain: "The principal procedure code is missing, incomplete, or invalid.",
    why: "An institutional claim's principal procedure couldn't be validated.",
    fix: "Add the correct principal procedure code and resubmit.",
    category: "coding",
  },
  {
    code: "MA130",
    system: "RARC",
    short: "Your claim contains incomplete and/or invalid information; no appeal rights — resubmit corrected.",
    plain: "The claim has missing/invalid data and was returned, not denied — fix and rebill.",
    why: "The payer rejected the claim up front for incomplete/invalid information, so there are no appeal rights — only correction.",
    fix: "Correct the identified information (see paired RARCs) and submit a new corrected claim.",
    category: "info",
  },
  {
    code: "N4",
    system: "RARC",
    short: "Missing/incomplete/invalid prior insurance carrier EOB.",
    plain: "The primary carrier's EOB is missing, incomplete, or invalid.",
    why: "A secondary claim needs the primary EOB attached, and it's missing or unreadable.",
    fix: "Attach a complete primary EOB/ERA and resubmit.",
    category: "cob",
  },
  {
    code: "N20",
    system: "RARC",
    short: "Service not payable with other service rendered on the same date.",
    plain: "This service can't be paid alongside another from the same day.",
    why: "A same-day edit makes the two services mutually exclusive as billed.",
    fix: "Verify the services and dates; use a modifier if appropriate, or accept the denial.",
    category: "coding",
  },
  {
    code: "N30",
    system: "RARC",
    short: "Patient ineligible for this service.",
    plain: "The patient wasn't eligible for this particular service.",
    why: "The member's plan or eligibility doesn't include this benefit/service.",
    fix: "Verify eligibility and benefits; if ineligible, bill the patient or correct the payer.",
    category: "coverage",
  },
  {
    code: "N56",
    system: "RARC",
    short: "Procedure code billed is not correct/valid for the services billed or the date of service.",
    plain: "The procedure code doesn't match the service actually provided or the date.",
    why: "The code billed is inconsistent with the documented service or wasn't valid for that date.",
    fix: "Recode to match the service and date of service, then resubmit.",
    category: "coding",
  },
  {
    code: "N115",
    system: "RARC",
    short: "Decision was based on a Local Coverage Determination (LCD).",
    plain: "An LCD policy drove this coverage decision.",
    why: "The contractor applied a Local Coverage Determination to decide medical necessity/coverage.",
    fix: "Read the cited LCD; if the service meets its criteria, appeal with documentation.",
    category: "coverage",
  },
  {
    code: "N130",
    system: "RARC",
    short: "Consult plan benefit documents/guidelines for information about restrictions for this service.",
    plain: "The plan's own benefit rules restrict this service — check them.",
    why: "Accompanies coverage adjustments where the answer lives in the member's specific plan documents.",
    fix: "Review the plan's benefit documents for the restriction; appeal or bill the patient based on what they say.",
    category: "coverage",
  },
  {
    code: "N179",
    system: "RARC",
    short: "Additional information has been requested from the member.",
    plain: "The payer is waiting on information from the patient.",
    why: "Processing is paused pending data the payer asked the member for (often COB).",
    fix: "Prompt the patient to respond to the payer's request, then have it reprocessed.",
    category: "info",
  },
  {
    code: "N180",
    system: "RARC",
    short: "This item or service does not meet the criteria for the category under which it was billed.",
    plain: "What you billed doesn't meet the requirements of the category it was billed under.",
    why: "The service was billed under a category whose coverage criteria it doesn't satisfy.",
    fix: "Confirm the correct billing category/code and documentation; correct and resubmit or appeal.",
    category: "coding",
  },
  {
    code: "N210",
    system: "RARC",
    short: "Alert: you may appeal this decision.",
    plain: "You have the right to appeal this determination.",
    why: "Informational alert confirming appeal rights for the adjustment.",
    fix: "File an appeal within the payer's deadline if you disagree.",
    category: "info",
  },
  {
    code: "N290",
    system: "RARC",
    short: "Missing/incomplete/invalid rendering provider primary identifier (NPI).",
    plain: "The rendering provider's NPI is missing, incomplete, or invalid.",
    why: "The rendering provider NPI couldn't be validated against the claim.",
    fix: "Add the correct rendering provider NPI and resubmit.",
    category: "info",
  },
  {
    code: "N362",
    system: "RARC",
    short: "The number of days or units exceeds the acceptable maximum.",
    plain: "You billed more days or units than the payer allows.",
    why: "A units/days edit (often MUE) capped the allowable quantity.",
    fix: "Verify the units against documentation; correct the count, or appeal with records if the quantity was warranted.",
    category: "coverage",
  },
  {
    code: "N382",
    system: "RARC",
    short: "Missing/incomplete/invalid patient identifier.",
    plain: "The patient identifier is missing, incomplete, or invalid.",
    why: "The patient/member ID didn't validate against the payer's records.",
    fix: "Correct the patient identifier to match the ID card and resubmit.",
    category: "info",
  },
  {
    code: "N522",
    system: "RARC",
    short: "This is a duplicate of a claim processed, or one currently being processed.",
    plain: "The payer already has this claim — it's a duplicate.",
    why: "Accompanies a duplicate adjustment (CARC 18): the claim matches one already on file.",
    fix: "Don't rebill. Track the original claim's status and follow up on that one.",
    category: "duplicate",
  },
  {
    code: "N657",
    system: "RARC",
    short: "This should have been billed with the appropriate code for these services.",
    plain: "A more appropriate code exists for what you billed.",
    why: "The payer indicates the service should have been reported under a different, correct code.",
    fix: "Identify the correct code for the documented service and resubmit a corrected claim.",
    category: "coding",
  },
];

/**
 * Slug used in the URL for a code — group-prefixed so it matches how analysts
 * search. CARC → "co-45", "pr-1"; RARC (no group) → "n130", "m15".
 */
export function codeSlug(c: DenialCode): string {
  return (c.group ? `${c.group}-${c.code}` : c.code).toLowerCase();
}

/** Display label including the typical group code, e.g. "CO-45" or "N130". */
export function codeLabel(c: DenialCode): string {
  return c.group ? `${c.group}-${c.code}` : c.code;
}

export function getDenialCode(slug: string): DenialCode | undefined {
  return DENIAL_CODES.find((c) => codeSlug(c) === slug.toLowerCase());
}

/** A few related codes — same category first, then fill from the same system. */
export function relatedCodes(c: DenialCode, n = 6): DenialCode[] {
  const others = DENIAL_CODES.filter((x) => x.code !== c.code);
  const sameCat = others.filter((x) => x.category === c.category);
  const rest = others.filter((x) => x.category !== c.category && x.system === c.system);
  return [...sameCat, ...rest].slice(0, n);
}
